#version 430

#define BLOCK_SIZE 32

layout( local_size_x = BLOCK_SIZE ) in;

layout( push_constant ) uniform params {
  uint len;
} PushConstant;

layout(std430, binding = 0) buffer a 
{
    float A[];
};

layout(std430, binding = 1) buffer b
{
    float B[];
};

shared float c;

void main() 
{
    if (gl_LocalInvocationID.x == 0) c = B[gl_WorkGroupID.x];
    barrier();
    A[gl_GlobalInvocationID.x] += c;
}