#version 430
#extension GL_GOOGLE_include_directive : require

#include "common.h"

layout( local_size_x = GRID_SIZE ) in;

layout( push_constant ) uniform params {
  uint len;
} PushConstant;

layout(std430, binding = 0) buffer a 
{
    float A[];
};

layout(std430, binding = 1) buffer b
{
    float B[];
};

shared float c;

void main() 
{
    if (gl_LocalInvocationID.x == 0) c = B[gl_WorkGroupID.x];
    barrier();
    A[gl_GlobalInvocationID.x] += c;
}